### PR TITLE
Fix for building URI templates vars w/ underscores

### PR DESCRIPTION
**Pull request by petejohanson**
* Don't eager calculate the match pattern, depend on lazy initalization
  in Expression#getMatchPattern().
* Add test to verify fix.

### CODE REVIEW

**Comment by petejohanson** [comment]
The reason this bombs in Expression#buildMatchingPattern() is because it attempts to use the variable name as the name of the named capture group, and "_" is not a valid character for a named capture group, so it throws.

By relying on lazy initialization in Expression#getMatchPattern(), we avoid hitting that problem for the simple builder case.

**Comment by damnhandy** [comment]
Thanks @petejohanson! Although, I'm curious as to why this hasn't come up when the tests are run. The uritemplatetest suite has names with underscores in it already and those are passing. I'm going to dig deeper before I accept.

**Comment by petejohanson** [comment]
Does the test suite use the builder at all? Or just parsing of existing Templates then processing?
On Nov 12, 2015 6:47 PM, "Ryan J. McDonough" <notifications@github.com> wrote:Thanks @petejohanson! Although, I'm curious as to why this hasn't come up when the tests are run. The uritemplatetest suite has names with underscores in it already and those are passing. I'm going to dig deeper before I accept.

**Comment by petejohanson** [comment]
https://github.com/damnhandy/Handy-URI-Templates/blob/master/src/test/java/com/damnhandy/uri/template/conformance/AbstractUriTemplateConformanceTest.java doesn't seem to use the builder at all, just parsing from existing template. Different code path?

**Comment by damnhandy** [comment]
I missed that part about it being related to the URI Template Builder. The conformance tests just focus on the template expansion. You fixe is a completely different code path. Accepting the PR. Thanks!

**Comment by petejohanson** [comment]
Any idea when you'll be doing the next release that includes this fix? Gauging whether I need to switch to -SNAPSHOT temporarily or not.

Thanks.

**Comment by damnhandy** [comment]
Just did :) 

https://github.com/damnhandy/Handy-URI-Templates/releases/tag/handy-uri-templates-2.1.1

Should be bubbling up to Maven Central now.

**Comment by petejohanson** [comment]
Perfect, thanks for the quick turn around!

**Pull request merged**
